# Our Open Food Network style guide.
#
# These are the rules we agreed upon and we work towards.
AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRailsVersion: 5.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    # Excluding: inadequate Naming/FileName rule rejects GemFile name with camelcase
    - 'engines/web/Gemfile'

## OFN SETTINGS
#
# Cop settings that have been agreed upon by the OFN community

Rails/SkipsModelValidations:
  AllowedMethods:
    - "touch"
    - "touch_all"
    - "update_all"
    - "update_attribute"
    - "update_column"
    - "update_columns"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/Send:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/LineLength:
  Enabled: true
  Max: 100

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false

## TEMPORARY/CONTESTED SETTINGS
#
# These are still to be decided upon, but recommended for inclusion by
# oeoeaio after scrutinising offenses the codebase

# Don't think this is a big issue, mostly picking up RPSEC scope definitions
# with lamdas and RSpec '.to change{}' blocks
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Heaps of offences (> 100) in specs, mostly in situations where two or more
# instances of a model are required, but only one is referenced. Difficult to
# fix without making the spec look messy or rewriting it.
# Should definitely fix at some point.
Lint/UselessAssignment:
  Exclude:
  - spec/**/*

Metrics/AbcSize:
  Enabled: true
  Max: 15

Metrics/BlockLength:
  Enabled: true
  Max: 25
  IgnoredMethods: [
    "class_eval",
    "collection",
    "context",
    "describe",
    "feature",
    "it",
    "member",
    "namespace",
    "resource",
    "resources",
    "scenario",
    "shared_examples",
  ]

Metrics/BlockNesting:
  Enabled: true
  Max: 3

Metrics/ClassLength:
  Enabled: true
  Max: 100

Metrics/ModuleLength:
  Enabled: true
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 6

Metrics/MethodLength:
  Enabled: true
  Max: 10

Metrics/ParameterLists:
  Enabled: true
  Max: 5

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 7

Naming/PredicateName:
  Enabled: false
